@startuml C4_Integration_Deployment_Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

title WoF Web App - Integration Deployment to a VPS

' Define the Person (User)
Person(player, "Player")

' Define the Internet as a global boundary (empty, just conceptual)
Deployment_Node(internet, "The Internet", "Public Network") {

}

' Integration Deployment (Strato VPS)

Deployment_Node(stratoVPS, "VPS Instance", "Ubuntu Server") {

    Deployment_Node(nginx, "Nginx Webserver", "Nginx", "Reverse Proxy & Static File Server") {
        Container(vpsFrontend, "Frontend App", "HTML5, CSS, JavaScript", "Served by Nginx")
        Container(vpsBackend, "Backend App", "Node.js, Express", "Reverse proxied by Nginx")
    }
    ContainerDb(vpsMariaDB, "MariaDB Database", "MariaDB", "DB instance on VPS")
    ContainerDb(vpsFilesystem, "Filesystem", "VPS Disk", "File storage on VPS")
}

' Relationships for Integration Deployment
Rel(player, internet, "Accesses", "HTTPS")
Rel(internet, nginx, "Routes traffic to", "Public IP (with DNS)")
Rel(nginx, vpsFrontend, "Serves", "HTTP/S")
Rel(nginx, vpsBackend, "Proxies requests to", "HTTP/S")
Rel(vpsFrontend, vpsBackend, "REST Calls") 
Rel(vpsBackend, vpsMariaDB, "Connects to", "JDBC/SQL")
Rel(vpsBackend, vpsFilesystem, "Accesses", "File I/O")

' Optional: Add a legend for clarity
SHOW_LEGEND()

@enduml